version: "3.7"
services:
  react-app:
    build: './react-app'
    image: gcr.io/scorecast-269923/scorecast-react-app
    ports: 
      - "80:80"
  express-app:
    container_name: express-app
    build: './express-app'
    ports:
      - "5000:5000"
