version: "3.7"
services:
  react-app:
    container_name: react-app
    build: './react-app'
    image: 'gcr.io/scorecast-269923/scorecast-react-app'
    ports: 
      - "80:80"

  data:
    container_name: data
    build: './data'
    image: 'gcr.io/scorecast-269923/scorecast-data'
