FROM alpine:3 as builder
COPY package.json yarn.lock ./
RUN apk add yarn
RUN yarn
COPY . ./
RUN yarn build

FROM nginx:1.16.1-alpine
COPY --from=builder /build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]